//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleapp.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Status { get; set; }
    
        public virtual Product_table Product_table { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
