//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleapp.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_table()
        {
            this.OrderTables = new HashSet<OrderTable>();
        }
    
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Type { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Items_In_Stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTables { get; set; }
    }
}
